#!/bin/sh

if [ -n "$BASH_SOURCE" ]; then
   THIS_SCRIPT_DIR="$(dirname $BASH_SOURCE)"
elif [ -n "$ZSH_NAME" ]; then
   THIS_SCRIPT_DIR="$(dirname $0)"
else
   THIS_SCRIPT_DIR="$(pwd)"
fi

TOP_DIR=$(realpath $THIS_SCRIPT_DIR)
TEMPLATECONF=$TOP_DIR/layers/meta-toradex-tezi/buildconf

if [ ! -r "$TOP_DIR/build/conf/local.conf" ]; then
    FIRST_TIME="yes"
fi

. $TOP_DIR/layers/openembedded-core/oe-init-build-env

if [ ! -z "$FIRST_TIME" ]; then
    cat <<EOM
Check and edit conf/local.conf to adapt to your local needs.
The following likely need your attention:
BB_NUMBER_THREADS, PARALLEL_MAKE, DL_DIR
EOM
fi
