#!/bin/sh

# Mount file systems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mkdir /dev/pts
mount -a

hostname -F /etc/hostname

# Create volatile directories
mkdir /var/volatile/tmp
mkdir /var/volatile/log
mkdir /run/lock

# Do not execute rc.local if rescueshell is defined
if grep -v -q rescueshell /proc/cmdline; then
	# Allow for distro or local customizations
	if [ -f /etc/rc.local ] ; then
		. /etc/rc.local
	fi
fi

echo
echo -e "\033[1mWelcome to the Toradex Easy Installer\033[0m"
echo
echo "This is a Linux based installer for Toradex modules. Currently, the installer"
echo "does not have a serial console interface. You can use the Toradex Easy Installer"
echo "via any of the available display interfaces using USB mouse/keyboard or via a"
echo "network connection using VNC. Use:"
echo "  # ip addr show"
echo "to display the Ethernet IP address(es) or use USB RNDIS at IP 192.168.11.1."
echo
echo "Check our documentation at:"
echo "  https://developer.toradex.com/software/toradex-easy-installer"

# Become session leader and try to find a real tty (e.g. ttyS0)
while true; do
	setsid cttyhack sh
	echo "Console sh exited with $?, respawning..."
	sleep 1
done
