#!/bin/sh

# Mount file systems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mkdir /dev/pts
mount -a

hostname -F /etc/hostname

# Create volatile directories
mkdir /var/volatile/tmp

# Do not execute rc.local if rescueshell is defined
if grep -v -q rescueshell /proc/cmdline; then
	# Allow for distro or local customizations
	if [ -f /etc/rc.local ] ; then
		. /etc/rc.local
	fi
fi

# Become session leader and try to find a real tty (e.g. ttyS0)
while true; do
	setsid cttyhack sh
	echo "Console sh exited with $?, respawning..."
	sleep 1
done
