#!/bin/sh

# Mount file systems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mkdir /dev/pts
mount -a

hostname -F /etc/hostname

# Create volatile directories
mkdir /var/volatile/tmp
mkdir /var/volatile/log
mkdir /run/lock

# Do not execute rc.local if rescueshell is defined
if grep -v -q rescueshell /proc/cmdline; then
	# Allow for distro or local customizations
	if [ -f /etc/rc.local ] ; then
		. /etc/rc.local
	fi
fi

echo
echo -e "\033[1mWelcome to Toradex Easy Installer\033[0m"
echo
echo "This is a Linux based installer for Toradex modules. Currently the"
echo "installer does not have a serial console interface. You can use the"
echo "Toradex Easy Installer through any of the available display interfaces"
echo "using USB mouse/keyboard or via network using VNC. Use:"
echo "  # ip addr show eth0"
echo "to display the Ethernet IP address or use USB RNDIS at IP 192.168.11.1."
echo

# Become session leader and try to find a real tty (e.g. ttyS0)
while true; do
	setsid cttyhack sh
	echo "Console sh exited with $?, respawning..."
	sleep 1
done
